### ISSUE TITLE
How to pass args to events

### ISSUE THREAD

**Issue by Xxpromw3mtxX** [zf-development/zf_context#2]
So I'm wondering how the args are passed to an event. I've tried in 2 ways still no result.
Can you help me understand how it works?
[](ur
![1e56896a35c8cb5778e66779c626e321](https://user-images.githubusercontent.com/32299416/133941374-c170ac77-6f74-464a-9d7b-e0db55b5f133.png)
l)

And behind this I have my eventhandler with the params set up but no result.

**Comment by zf-development** [comment]
Hi! Here's an example one how to use it. 

´´´
RegisterNetEvent('atlantis_blackmarket:buyItem')
AddEventHandler('atlantis_blackmarket:buyItem', function(datas)
  print(data.item)
  print(data.quantity)
  print(data.price)
end)
´´´
Menu Array will look like this
´´´
  {
    header = 'Lockpick',
    text = 'Buy a lockpick for 5$',
    datas = {
      event = 'atlantis_blackmarket:buyItem',
      args = {
        item = 'lockpick',
        quantity = 1,
        price = 5
      }
    }
  }
´´´

**Comment by Xxpromw3mtxX** [comment]
Hi! Thank for the fast reply!
I'll try in a bit again and I'll let you know! :D

**Comment by zf-development** [comment]
No problem. It could have been faster if I would not have been on my phone 😅

**Comment by Xxpromw3mtxX** [comment]
I can even let the player choose the quantity?

**Comment by Xxpromw3mtxX** [comment]
No worries :P

**Comment by zf-development** [comment]
It's just an exemple because it's a button so it's for actionning functions more then passing variable datas but you could open a zf dialog menu via the context menu and ask for a quantity.

**Comment by Xxpromw3mtxX** [comment]
oh okok

**Comment by Xxpromw3mtxX** [comment]
Ok so I'm trying but still no printing to the console that's kinda strange

**Comment by zf-development** [comment]
Could you give me the code of the menu option and the event so i can see?

**Comment by Xxpromw3mtxX** [comment]
Yup, here it is
![191b638b6aca4654b06cbfe9c0a27d2a](https://user-images.githubusercontent.com/32299416/133941870-0e070bfd-6ea0-4e10-be4f-417919de4f03.png)

It feels like that when I click nothing happens

**Comment by Xxpromw3mtxX** [comment]
it works when I use the E to open the contextmenu but then when clicking on items nothing

**Comment by zf-development** [comment]
Hi! We've just release a new update with a FULL example for usage. Should take a look and I should fix all your problems
