### ISSUE TITLE
help for qb-apartments

### ISSUE THREAD

**Issue by MahmoodHensem** [zf-development/zf_context#3]
![image](https://user-images.githubusercontent.com/88893827/135225379-215eab60-6c2e-42fe-aa0c-9f8b7fb0718e.png)
i want to change default qb menu into zx_context .. Someone help me 😥😥
![image](https://user-images.githubusercontent.com/88893827/135225511-753871f4-853d-431a-b84b-2d57aaf0605a.png)

**Comment by MahmoodHensem** [comment]
only enter apartments work.. i want to make ring doorbell work too

**Comment by zf-development** [comment]
You are not usign zf_context. Please go ask help at good place.

**Comment by MahmoodHensem** [comment]
i use zf_context [image: image.png] i ask.. how cann i change the doorbell
default menu to zf_context

**Comment by MahmoodHensem** [comment]
the list of apartment owner
